sonar.exclusions=tests/**/*,src/**/*.*,src/BL/analytics_bl.py,src/**,src/**/*
sonar.cpd.exclusions=src/**/*.*,src/main.py
sonar.coverage.exclusions=src/**,src/**/*,tests/**/*.*,src/main.py,src/utilities/logging_utils.py,src/Orchestrator/amend_orchestrator.py,src/*,src/Prompts/*,src/DAL/*,src/BL/*,src/Config/*,src/Models/*,src/Streamlit/*,src/Orchestrator/*,src/Schemas/*,src/connectors/*,src/Exception/*,src/utilities/*,src/BL/analytics_bl.py, src/utils/*, src/commons/get_config.py,src/constants/__init__.py

sonar.issue.ignore.multicriteria=e1,e2, e3

sonar.issue.ignore.multicriteria.e1.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.e2.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.py

sonar.issue.ignore.multicriteria.e3.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.py

