apiVersion: v1
kind: ConfigMap
metadata:
  name: #{AppName}-config
  namespace: #{Namespace}
data:
  #All application level configuration will be defined here. This will be referenced in the deployment yaml file
  APP_NAME: #{AppName}
  AppId: #{AppId}
  AppGroupId: #{AppGroupId}
  RegionId: #{RegionId}
  TCSUrl: #{TCSUrl}
  ACSClientId: #{ACSClientId}

  AZURE_OPENAI_ENDPOINT: #{AZURE_OPENAI_ENDPOINT}
  OPENAI_API_KEY: #{OPENAI_API_KEY}
  OPENAI_API_VERSION: #{OPENAI_API_VERSION}
  OPENAI_API_TYPE: #{OPENAI_API_TYPE}

  JIRA_SERVER: #{JIRA_SERVER}
  CONFLUENCE_SERVER: #{CONFLUENCE_SERVER}
  JIRA_USERNAME: #{JIRA_USERNAME}
  JIRA_API_TOKEN: #{JIRA_API_TOKEN}

  MONGO_CONN_STRING: #{MONGO_CONN_STRING}
  MONGO_DB_NAME: #{MONGO_DB_NAME}
  MONGO_COLLECTION_NAME: #{MONGO_COLLECTION_NAME}

  LLAMA_BASE_KEY: #{LLAMA_BASE_KEY}
  LLAMA_MODEL: #{LLAMA_MODEL}
