apiVersion: v1
kind: PersistentVolume
metadata:
  name: #{AppName}-pv
  namespace: #{Namespace}
  labels:
    app: #{AppName}-pv
spec:
  capacity:
    storage: #{StorageCapacity}
  accessModes:
    - #{AccessModes}
  persistentVolumeReclaimPolicy: #{persistentVolumeReclaimPolicy}
  azureFile:
    secretName: #{AppName}-secret
    shareName: #{FileShareName}
    readOnly: false
